[package]
name = "mkit"
version = "0.1.0"
description = "Tools and macros for inter-planetary applications"
repository = "https://github.com/bnclabs/mkit"
authors = ["prataprc <prataprc@gmail.com>"]
keywords = ["data", "cbor"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/mkit/"
edition = "2018"

[dependencies]
log = "0.4.8"
mkit-derive = { path = "mkit-derive", version = "=0.1.0"}
