[package]
name = "ip-tools"
version = "0.1.0"
description = "Tools and macros for inter-planetary applications"
repository = "https://github.com/bnclabs/ip-tools"
authors = ["prataprc <prataprc@gmail.com>"]
keywords = ["data", "cbor"]
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/ip-tools/"
edition = "2018"

[dependencies]
# ip-derive = { path = "ip-derive", version = "=0.1.0"}
